baseurl = "http://www.fangedgames.com/"
languageCode = "en-us"
title = "Fanged Games"

[Params]
Author = "Matteo Suppo"
DisqusShortname = "fangedgames"
AnalyticsID = "UA-80263861-1"
Summary = true

[[menu.main]]
name = "Home"
weight = -110
identifier = "home"
url = "/"
